public class Solution {
	//Iterate through all numbers from 2 to num, for each one of the number, 
	//it is generated by n/2 by shifting left and add zero or one.
    public int[] countBits(int num) {
    	int[] result = new int[num+1];
    	
    	for(int i = 1; i <= num; i++) {
    		result[i] = i % 2 == 0 ? result[i/2]: result[i/2] + 1;
    	}

    	return result;
    }
}